import { Title, Page, Wrapper } from '../../components'
import { Spacer } from '../../components/Spacer.tsx'

const About = () => {
  return (
    <Wrapper>
      <Spacer wide />
      <div className="flex justify-center">
        <Title>about</Title>
      </div>
      <Spacer wide />
      <p>This site was generated by Next.js.</p>
      <Spacer wide />
    </Wrapper>
  )
}

About.getLayout = (page) => (
  <Page title="About" pagePath="/about">
    {page}
  </Page>
)

export default About
