language: node_js
cache: yarn
node_js:
- node
before_script:
- http-server public &
script:
- npm run build:ci
notifications:
  webhooks: http://jsonnull.com:82/webhook
  slack:
    secure: STsWxtDGWw8d2cl0JPkX3Hqvsf+gt/4JAkbZ+GYr06EpVmAha/CRxt2SMIbBBLaP2MWEpIkotZ5NEnNivwWSaS/mISEt2zQdVa3gEj5JGh7h0fu3DN5DmVN9n5XPgljalWsa713JjTsY7MIpF+DHhjgJrPSuoMmSnGHHA+hjvtbOWy2ogE//Mbz3yoT+riKICjqnlBoNUxdeQQ1v4Rnq8TMycDdXJylrLui45L+fYZfKVw80k2q6uLimwiFUILz8+QXI0znWfd7K8auWBj4plsNW+E9hpVP1zmQA30nEETxUGar4frqZrcscZg1505HejZsPCKOsp+tY2+zQBC2jQh0K+aIbtWqAW1KkMLSBh83dNZlPWX8UyIXeX6yUcEv7gUJvnvf6qGD5+JEGgSIrcigkFeQqsv/FXOdxY4XaMsaZVYI5hURD+GrS8ndMLosViXp//uTzN41J/mPiTZERT8yGob39htguedvxQMeiuz0wCOVpenQKV5udoaaAAV+7jBequ1xX5/X4hB97R8aec5TCLyICWiKfazb0qyrrar2RRXQKerDAyjT6307cuIJ+dXQol1FSsqcwuX822VrGLge5CTUPaYuvF1jIt44ECA/dPcHbj4X9Elu8FUwuynJp4ty3U2Jycb+0HsbqzBFXNxe2VLE5sPI5sPajerZKp3k=
