language: node_js
cache: yarn
node_js:
- node
addons:
  ssh_known_hosts: jsonnull.com
before_install:
- yarn global add greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- http-server public &
script:
- npm run build:ci
after_script: greenkeeper-lockfile-upload
before_deploy:
- openssl aes-256-cbc -K $encrypted_cbaed4db383c_key -iv $encrypted_cbaed4db383c_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: ssh root@jsonnull.com "cd jsonnull.com && docker-compose run deploy && docker-compose restart server"
  on:
    branch: master
notifications:
  slack:
    secure: STsWxtDGWw8d2cl0JPkX3Hqvsf+gt/4JAkbZ+GYr06EpVmAha/CRxt2SMIbBBLaP2MWEpIkotZ5NEnNivwWSaS/mISEt2zQdVa3gEj5JGh7h0fu3DN5DmVN9n5XPgljalWsa713JjTsY7MIpF+DHhjgJrPSuoMmSnGHHA+hjvtbOWy2ogE//Mbz3yoT+riKICjqnlBoNUxdeQQ1v4Rnq8TMycDdXJylrLui45L+fYZfKVw80k2q6uLimwiFUILz8+QXI0znWfd7K8auWBj4plsNW+E9hpVP1zmQA30nEETxUGar4frqZrcscZg1505HejZsPCKOsp+tY2+zQBC2jQh0K+aIbtWqAW1KkMLSBh83dNZlPWX8UyIXeX6yUcEv7gUJvnvf6qGD5+JEGgSIrcigkFeQqsv/FXOdxY4XaMsaZVYI5hURD+GrS8ndMLosViXp//uTzN41J/mPiTZERT8yGob39htguedvxQMeiuz0wCOVpenQKV5udoaaAAV+7jBequ1xX5/X4hB97R8aec5TCLyICWiKfazb0qyrrar2RRXQKerDAyjT6307cuIJ+dXQol1FSsqcwuX822VrGLge5CTUPaYuvF1jIt44ECA/dPcHbj4X9Elu8FUwuynJp4ty3U2Jycb+0HsbqzBFXNxe2VLE5sPI5sPajerZKp3k=
env:
  global:
    secure: Gh7Djusizxstop9IFl6GjZ7C162kmaKNmGJ2tPVl3PAmUqzPTKQdlzTtykCDNPPcYZESaYX4kiJr8JDKmHHs8EQTd2hWJ5tKxKeV02rfEX017Cb2z3dqwZU00cIi2zPzMF7YaBr3QKfs1MQeHX5Tfx+r+xBedkLJEQMDJccZJofszAWqfd9cuvSR68u/jBrtUYSw/V8Nj/XDucaEwN+meNSMCIlOE4cxZG8C5SQPbYdD/ZzGRfZN7kdHCztGzRgi+pGYYj0G1UX1TheZzfAUUzwtwysnvM8WASUJcw924kY+aVtJSS0fdau1ELjzq0JYeC/c4B5qRCHs04PuAUCt8mYysA5bGiTkmAzauYx0C++74sVS2x5BMsF+OiIZA9iaDTKVA1NQNvo3N5JgpQdA9kCLVQjhLKJDUkXwBXJmEbo7o21Jit+6JrF9y99mX5FuxyxVkALmlrGZetbIxXGYy75cYljEjhK5U3MPBF8nCI1xa1YWagGx4khuYgecyaNDSAZFm+wE7woGOk1wb6PU1PBpRkgykpUhx6y+zGjeG4lvcHWKwB4dBRZeNCgMLUm68vGKXPWdYbEzA6gBPoU8bY8Ck4rpvvbn9VdK5TRu+TuKGmvFp5B2loaxmqAL6Zb/o5wMSzV4RWet5Gf4oWsAu5LDLOCyuZ4ZBXnMgQWyORk=
