version: "3"
services:
  server:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ~/.caddy:/root/.caddy
      - ./public:/srv
    ports:
      - 80:80
      - 443:443
    restart: always
  cd:
    build: .
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 82:80
    restart: always
