version: "3"
services:
  server:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ~/.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
  build:
    image: node:alpine 
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: sh -c "rm -rf ./public && yarn install --frozen-lockfile --production=false && yarn run build:production"
