[build]
publish = ".next"
command = "yarn build"

[build.environment]
YARN_VERSION = "3.1.1"
YARN_ENABLE_GLOBAL_CACHE = "true"
YARN_GLOBAL_FOLDER = "/opt/buildhome/.yarn_cache"

[[plugins]]
package = "@netlify/plugin-nextjs"
