// flow-typed signature: 00d5f7d6b15e16983455cb2c0955cb7f
// flow-typed version: <<STUB>>/feather-icons_v^3.2.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feather-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feather-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feather-icons/dist/feather' {
  declare module.exports: any;
}

declare module 'feather-icons/dist/feather.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feather-icons/dist/feather.js' {
  declare module.exports: $Exports<'feather-icons/dist/feather'>;
}
declare module 'feather-icons/dist/feather.min.js' {
  declare module.exports: $Exports<'feather-icons/dist/feather.min'>;
}
